# Nova AI Assistant Default Configuration

# Chat behavior settings
chat:
  history_dir: "~/.nova/history"
  max_history_length: 50  # Maximum messages to include in context
  auto_save: true

# AI profiles for different models and providers
profiles:
  default:
    name: "default"
    provider: "openai"
    model_name: "gpt-3.5-turbo"
    max_tokens: 2000
    temperature: 0.7
    # api_key will be set via environment variables
    
  gpt4:
    name: "gpt4"
    provider: "openai"
    model_name: "gpt-4"
    max_tokens: 4000
    temperature: 0.7
    
  claude:
    name: "claude"
    provider: "anthropic"
    model_name: "claude-sonnet-4-20250514"
    max_tokens: 4000
    temperature: 0.7
    
  claude-opus:
    name: "claude-opus"
    provider: "anthropic"
    model_name: "claude-opus-4-20250514"
    max_tokens: 4000
    temperature: 0.7
    
  llama:
    name: "llama"
    provider: "ollama"
    model_name: "llama3.1"
    base_url: "http://localhost:11434"
    max_tokens: 2000
    temperature: 0.7

# Active profile (defaults to "default" if not specified)
active_profile: "default"

# Memory Management Features:
# - Conversation summarization for long chats (/summarize command)
# - Smart context optimization with token limit awareness
# - Message importance scoring for better context retention
# - Conversation tags and categorization (/tag command)
# - Memory statistics and analysis (/stats command)
# - Automatic suggestions for conversation organization

# Environment Variables for API Keys:
# - NOVA_API_KEY: General API key override
# - OPENAI_API_KEY: OpenAI-specific API key
# - ANTHROPIC_API_KEY: Anthropic-specific API key
# - NOVA_PROFILE: Override active profile
# - OLLAMA_HOST: Ollama server URL override